org: drochag1
app: worldtime
service: api

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  environment:
    GOOGLE_MAPS_API_KEY: ${param:GOOGLE_MAPS_API_KEY}

functions:
  getPlaces:
    handler: handler.getPlaces
    events:
      - http:
          path: /get-places
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Requested-With
              - Accept
              - Origin
              - Access-Control-Allow-Origin
  getExtendedSuggestion:
    handler: handler.getExtendedSuggestion
    events:
      - http:
          path: /get-extended-suggestion
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Requested-With
              - Accept
              - Origin
              - Access-Control-Allow-Origin

plugins:
  - serverless-offline
